### ISSUE TITLE
New Product Component v0

### ISSUE THREAD

**Issue by arantespp** [Joaopdev/MarketPlace#12]
# Description

Create the `NewProductForm` version zero. We'll only create one single field of the form: `name`. Once we complete the basic UI and the validators structure, we add the remaining fields. Some libraries handle forms using React, as [React Hook Form](https://react-hook-form.com/) and [Formik](https://formik.org/)

![image](https://user-images.githubusercontent.com/16626980/130717248-80420627-5ae1-442d-9877-4e29c5fed104.png)

# Goals

- Learn forms with React.

# Tasks

- [ ] Create `Input` component.
- [ ] Create `NewProductForm` component UI.
- [ ] Chose and add form libraries to handle the form flow (React Hook Form, Formik,...)
- [ ] Name field must be required.
- [ ] An error should appear if the user tries to submit the form with `name` empty.
